server:
  port: 8084

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  token:
    signature: secretKeyForFootballBalancerTestPassword
    expiration: 180

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/footballequalizer?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: footballEqualizer_user
    password: footballEqualizer_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs/${spring.application.name}

